-- DesignerSale.com.au Database Schema Migration
-- Upgrades prototype tables and creates the designer boutique aggregator schema

-- 1. Ensure profiles has is_admin column
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS is_admin boolean DEFAULT false;

-- 2. Create is_admin() helper function
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.profiles 
    WHERE id = auth.uid() AND is_admin = true
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 3. Create merchants table
CREATE TABLE IF NOT EXISTS public.merchants (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  logo_url text,
  website_url text NOT NULL,
  description text,
  category_ids integer[],
  location_city text,
  location_state text,
  social_instagram text,
  status text DEFAULT 'active' CHECK (status IN ('active', 'draft', 'archived')),
  affiliate_url_template text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  created_by uuid REFERENCES auth.users ON DELETE SET NULL
);

-- Enable RLS for merchants
ALTER TABLE public.merchants ENABLE ROW LEVEL SECURITY;

-- Policies for merchants
CREATE POLICY "Merchants are viewable by everyone" ON public.merchants 
  FOR SELECT USING (true);

CREATE POLICY "Merchants are manageable by admins" ON public.merchants 
  FOR ALL USING (public.is_admin());

-- 4. Create sales_secure table
CREATE TABLE IF NOT EXISTS public.sales_secure (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  merchant_id bigint REFERENCES public.merchants(id) ON DELETE CASCADE NOT NULL,
  title text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  teaser_text text,
  sale_url text NOT NULL,
  discount_min_pct integer,
  discount_max_pct integer,
  price_range_min numeric,
  price_range_max numeric,
  sale_start_date date NOT NULL,
  sale_end_date date,
  category_ids integer[],
  image_urls text[],
  is_featured boolean DEFAULT false NOT NULL,
  status text DEFAULT 'active' CHECK (status IN ('active', 'draft', 'archived', 'expired')),
  last_verified_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  created_by uuid REFERENCES auth.users ON DELETE SET NULL
);

-- Enable RLS for sales_secure
ALTER TABLE public.sales_secure ENABLE ROW LEVEL SECURITY;

-- Policies for sales_secure
CREATE POLICY "Active sales are viewable by everyone" ON public.sales_secure 
  FOR SELECT USING (status = 'active' OR public.is_admin());

CREATE POLICY "Sales are manageable by admins" ON public.sales_secure 
  FOR ALL USING (public.is_admin());

-- 5. Prepare and transition products table
-- Check if products already exists and rename to products_secure
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'products') AND 
     NOT EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'products_secure') THEN
    ALTER TABLE public.products RENAME TO products_secure;
  END IF;
END $$;

-- Alter products_secure to support expanded designer boutique fields
ALTER TABLE public.products_secure ADD COLUMN IF NOT EXISTS merchant_id bigint REFERENCES public.merchants(id) ON DELETE SET NULL;
ALTER TABLE public.products_secure ADD COLUMN IF NOT EXISTS sale_id bigint REFERENCES public.sales_secure(id) ON DELETE SET NULL;
ALTER TABLE public.products_secure ADD COLUMN IF NOT EXISTS slug text;
ALTER TABLE public.products_secure ADD COLUMN IF NOT EXISTS teaser_text text;
ALTER TABLE public.products_secure ADD COLUMN IF NOT EXISTS compare_at_price numeric;
ALTER TABLE public.products_secure ADD COLUMN IF NOT EXISTS sku text;
ALTER TABLE public.products_secure ADD COLUMN IF NOT EXISTS stock_qty integer DEFAULT 0;
ALTER TABLE public.products_secure ADD COLUMN IF NOT EXISTS stripe_price_id text;
ALTER TABLE public.products_secure ADD COLUMN IF NOT EXISTS category_ids integer[];
ALTER TABLE public.products_secure ADD COLUMN IF NOT EXISTS image_urls text[];
ALTER TABLE public.products_secure ADD COLUMN IF NOT EXISTS is_external boolean DEFAULT false;
ALTER TABLE public.products_secure ADD COLUMN IF NOT EXISTS external_url text;
ALTER TABLE public.products_secure ADD COLUMN IF NOT EXISTS last_verified_at timestamp with time zone;
ALTER TABLE public.products_secure ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT timezone('utc'::text, now());
ALTER TABLE public.products_secure ADD COLUMN IF NOT EXISTS created_by uuid REFERENCES auth.users ON DELETE SET NULL;
ALTER TABLE public.products_secure ADD COLUMN IF NOT EXISTS status text DEFAULT 'active' CHECK (status IN ('active', 'draft', 'archived'));

-- Populate slug for products_secure if NULL
UPDATE public.products_secure SET slug = LOWER(REPLACE(name, ' ', '-')) WHERE slug IS NULL;

-- Enable RLS for products_secure
ALTER TABLE public.products_secure ENABLE ROW LEVEL SECURITY;

-- Policies for products_secure
CREATE POLICY "Active products are viewable by everyone" ON public.products_secure 
  FOR SELECT USING (status = 'active' OR public.is_admin());

CREATE POLICY "Products are manageable by admins" ON public.products_secure 
  FOR ALL USING (public.is_admin());

-- 6. Create Gated Views with Column Masking
-- For Sales
CREATE OR REPLACE VIEW public.sales AS
SELECT 
  id, merchant_id, title, slug, teaser_text, discount_min_pct, discount_max_pct, sale_start_date, sale_end_date, category_ids, image_urls, is_featured, status, last_verified_at, created_at, updated_at, created_by,
  CASE WHEN auth.role() = 'authenticated' THEN description ELSE NULL END AS description,
  CASE WHEN auth.role() = 'authenticated' THEN sale_url ELSE NULL END AS sale_url,
  CASE WHEN auth.role() = 'authenticated' THEN price_range_min ELSE NULL END AS price_range_min,
  CASE WHEN auth.role() = 'authenticated' THEN price_range_max ELSE NULL END AS price_range_max
FROM public.sales_secure;

-- For Products
CREATE OR REPLACE VIEW public.products AS
SELECT
  id, name, category, image_url, rating, created_at, merchant_id, sale_id, slug, teaser_text, compare_at_price, sku, is_external, updated_at, created_by, status,
  CASE WHEN auth.role() = 'authenticated' THEN price ELSE NULL END AS price,
  CASE WHEN auth.role() = 'authenticated' THEN description ELSE NULL END AS description,
  CASE WHEN auth.role() = 'authenticated' THEN stock_qty ELSE NULL END AS stock_qty,
  CASE WHEN auth.role() = 'authenticated' THEN stripe_price_id ELSE NULL END AS stripe_price_id,
  CASE WHEN auth.role() = 'authenticated' THEN external_url ELSE NULL END AS external_url
FROM public.products_secure;

-- 7. Create affiliate_clicks table
CREATE TABLE IF NOT EXISTS public.affiliate_clicks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE SET NULL,
  sale_id bigint REFERENCES public.sales_secure(id) ON DELETE SET NULL,
  product_id bigint REFERENCES public.products_secure(id) ON DELETE SET NULL,
  merchant_id bigint REFERENCES public.merchants(id) ON DELETE CASCADE NOT NULL,
  clicked_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  referrer_url text,
  session_id text
);

-- Enable RLS for affiliate_clicks
ALTER TABLE public.affiliate_clicks ENABLE ROW LEVEL SECURITY;

-- Policies for affiliate_clicks
CREATE POLICY "Admins can view clicks" ON public.affiliate_clicks 
  FOR SELECT USING (public.is_admin());

CREATE POLICY "Anyone can insert click tracking logs" ON public.affiliate_clicks 
  FOR INSERT WITH CHECK (true);

-- 8. Create automation_flags table
CREATE TABLE IF NOT EXISTS public.automation_flags (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type text CHECK (entity_type IN ('sale', 'product')) NOT NULL,
  entity_id bigint NOT NULL,
  flag_type text CHECK (flag_type IN ('expired_date', 'suspected_stale', 'out_of_stock')) NOT NULL,
  raw_signal text,
  flagged_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  reviewed_by uuid REFERENCES auth.users ON DELETE SET NULL,
  reviewed_at timestamp with time zone,
  action_taken text CHECK (action_taken IN ('unpublished', 'marked_ok', 'dismissed'))
);

-- Enable RLS for automation_flags
ALTER TABLE public.automation_flags ENABLE ROW LEVEL SECURITY;

-- Policies for automation_flags
CREATE POLICY "Automation flags are manageable by admins" ON public.automation_flags 
  FOR ALL USING (public.is_admin());

-- 9. Add category fields for parent and icon
ALTER TABLE public.categories ADD COLUMN IF NOT EXISTS parent_id integer REFERENCES public.categories(id) ON DELETE SET NULL;
ALTER TABLE public.categories ADD COLUMN IF NOT EXISTS icon_url text;

-- 10. Seed Initial Premium Australian Designer Boutique Data
-- Clear old products to allow clean setup (optional but recommended for complete transformation)
DELETE FROM public.products_secure;

-- Insert categories if not present
INSERT INTO public.categories (name, slug, description)
VALUES 
('Womenswear', 'womenswear', 'Designer dresses, skirts, tops, and statements'),
('Menswear', 'menswear', 'Premium tailoring, shirts, trousers, and casuals'),
('Accessories', 'accessories', 'Luxury leather bags, belts, sunglasses, and hats'),
('Jewellery', 'jewellery', 'Fine designer earrings, necklaces, rings, and watches')
ON CONFLICT (id) DO NOTHING;

-- Insert Merchants
INSERT INTO public.merchants (name, slug, logo_url, website_url, description, location_city, location_state, status, affiliate_url_template)
VALUES 
('Zimmermann', 'zimmermann', 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&q=80&w=300', 'https://www.zimmermann.com', 'Sophisticated femininity, clever colour combinations and delicate original prints.', 'Sydney', 'NSW', 'active', 'https://zimmermann.com/affiliate?url={{link}}'),
('Scanlan Theodore', 'scanlan-theodore', 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&q=80&w=300', 'https://www.scanlantheodore.com', 'Modern, elegant and timeless luxury fashion for women.', 'Melbourne', 'VIC', 'active', 'https://scanlantheodore.com/affiliate?url={{link}}'),
('AJE', 'aje', 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&q=80&w=300', 'https://www.ajeworld.com.au', 'Effortless cool, tough femininity and dualities of style.', 'Brisbane', 'QLD', 'active', 'https://ajeworld.com.au/affiliate?url={{link}}')
ON CONFLICT DO NOTHING;

-- Insert Sales (Seed data into sales_secure)
DO $$
DECLARE
  zim_id bigint;
  scan_id bigint;
  aje_id bigint;
  cat_womens_id integer;
  cat_acc_id integer;
BEGIN
  SELECT id INTO zim_id FROM public.merchants WHERE slug = 'zimmermann';
  SELECT id INTO scan_id FROM public.merchants WHERE slug = 'scanlan-theodore';
  SELECT id INTO aje_id FROM public.merchants WHERE slug = 'aje';
  SELECT id INTO cat_womens_id FROM public.categories WHERE slug = 'womenswear';
  SELECT id INTO cat_acc_id FROM public.categories WHERE slug = 'accessories';

  IF zim_id IS NOT NULL THEN
    INSERT INTO public.sales_secure (merchant_id, title, slug, description, teaser_text, sale_url, discount_min_pct, discount_max_pct, price_range_min, price_range_max, sale_start_date, sale_end_date, category_ids, image_urls, is_featured, status)
    VALUES 
    (zim_id, 'Zimmermann Resort Sale', 'zimmermann-resort-sale', 'Save on iconic floral resort dresses, skirts, and swimwear from recent collections. Limited stock available.', 'Up to 50% off premium Zimmermann resort wear.', 'https://www.zimmermann.com/sale', 20, 50, 250.00, 890.00, CURRENT_DATE - 2, CURRENT_DATE + 5, ARRAY[cat_womens_id], ARRAY['https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&q=80&w=800'], true, 'active'),
    (scan_id, 'Scanlan Theodore Autumn Archive', 'scanlan-theodore-autumn-archive', 'Exclusive discounts on knitwear, structured tailoring, and luxury silk dresses.', 'Up to 40% off high-end Australian tailoring.', 'https://www.scanlantheodore.com/collections/sale', 15, 40, 180.00, 650.00, CURRENT_DATE - 1, CURRENT_DATE + 10, ARRAY[cat_womens_id], ARRAY['https://images.unsplash.com/photo-1485968579580-b6d095142e6e?auto=format&fit=crop&q=80&w=800'], true, 'active'),
    (aje_id, 'AJE Outerwear & Bag Event', 'aje-outerwear-bag-event', 'Seasonal markdown on signature AJE linen jackets, puff sleeve dresses, and leather clutches.', 'Up to 30% off linen and leather staples.', 'https://www.ajeworld.com.au/collections/sale', 10, 30, 120.00, 420.00, CURRENT_DATE, CURRENT_DATE + 4, ARRAY[cat_womens_id, cat_acc_id], ARRAY['https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&q=80&w=800'], false, 'active')
    ON CONFLICT DO NOTHING;

    -- Insert Products (Seed data into products_secure)
    INSERT INTO public.products_secure (merchant_id, name, slug, description, teaser_text, price, compare_at_price, sku, stock_qty, category_ids, image_urls, image_url, is_external, external_url, status, rating, is_featured)
    VALUES
    (zim_id, 'Luminosity Floral Midi Dress', 'luminosity-floral-midi-dress', 'Delicate silk midi dress featuring Zimmermann signature custom placements, tiered skirting and custom belt.', 'Stunning silk midi dress featuring signature custom placements.', 595.00, 1100.00, 'ZIM-LUM-001', 5, ARRAY[cat_womens_id], ARRAY['https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&q=80&w=600'], 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&q=80&w=600', false, NULL, 'active', 5.0, true),
    (scan_id, 'Crepe Knit Tailored Jacket', 'crepe-knit-tailored-jacket', 'Structured Scanlan Theodore crepe knit signature blazer. Double-breasted design with metallic hardware.', 'Structured crepe knit signature blazer in double-breasted design.', 390.00, 650.00, 'ST-CRK-002', 12, ARRAY[cat_womens_id], ARRAY['https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&q=80&w=600'], 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&q=80&w=600', false, NULL, 'active', 4.8, true),
    (aje_id, 'Signature Logo Canvas Tote', 'signature-logo-canvas-tote', 'Sturdy premium canvas tote with hand-stitched leather panels and gold signature AJE lettering.', 'Premium canvas tote bag with robust hand-stitched leather panels.', 195.00, 275.00, 'AJE-TOT-003', 0, ARRAY[cat_acc_id], ARRAY['https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&q=80&w=600'], 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&q=80&w=600', true, 'https://www.ajeworld.com.au/products/signature-logo-canvas-tote', 'active', 4.9, false);
  END IF;
END $$;

-- 11. Ensure site_settings has AUD and is correct for DesignerSale
UPDATE public.site_settings
SET currency = 'AUD',
    store_name = 'DesignerSale.com.au',
    support_email = 'support@designersale.com.au',
    footer_config = '{"copyright": "© 2026 DesignerSale.com.au. All rights reserved.", "description": "Australia''s premier designer boutique sale aggregator. Discover luxury fashion markdowns and boutique sales in one place."}'::jsonb,
    header_config = '{"logo": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&q=80&w=300", "top_bar": "Free Sign Up to Unlock Gated Designer Sales & Prices!", "nav_links": [{"label": "Home", "url": "/"}, {"label": "Sales & Deals", "url": "/sales"}, {"label": "Boutiques", "url": "/merchants"}, {"label": "Direct Shop", "url": "/shop"}, {"label": "About Us", "url": "/about"}]}'::jsonb
WHERE id = 1;
